server:
  port: 6001
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hezhe1688/microservicecloud-config.git #GitHub上面的git仓库名字
  application:
    name: micerservicecloud-config


